import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { ArrowLeft, ArrowRight, Check, CloudOff, ImagePlus, LogOut, Package, Plus, Search, Sprout, Truck, Users } from 'lucide-react'
import { api } from './api'
import type { Listing, Offer, Order, Role, Session } from './api'
import { translations } from './i18n'
import { phase2Text } from './phase2Translations'
import { phase3Text } from './phase3Translations'
import { MarketPrices } from './marketPrices'
import { LogisticsHub, RequestHistory, StorageRequestForm, TransportRequestForm } from './logistics'
import { phase4Text } from './phase4Translations'
import { phase5Text } from './phase5Translations'
import { CropAssistance } from './cropAssistance'
import type { Language } from './i18n'
import './App.css'
import './marketplace.css'

type Page = 'home' | 'auth' | 'farmer' | 'buyer' | 'listing' | 'browse' | 'offer' | 'offers' | 'orders' | 'market-prices' | 'storage' | 'storage-request' | 'storage-requests' | 'transport' | 'transport-request' | 'transport-requests' | 'crop-assistance'
type AuthMode = 'register' | 'login'
const sessionFromStorage = () => { try { return JSON.parse(localStorage.getItem('agriconnect-session') || 'null') as Session | null } catch { return null } }

export default function App() {
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('agriconnect-language') as Language) || 'en')
  const [session, setSession] = useState<Session | null>(sessionFromStorage)
  const [page, setPage] = useState<Page>(() => sessionFromStorage() ? (sessionFromStorage()!.user.role === 'FARMER' ? 'farmer' : 'buyer') : 'home')
  const [role, setRole] = useState<Role>('FARMER')
  const [authMode, setAuthMode] = useState<AuthMode>('register')
  const [selectedListing, setSelectedListing] = useState<Listing | null>(null)
  const copy = { ...translations[language], ...phase2Text[language], ...phase3Text[language], ...phase4Text[language], ...phase5Text[language] } as Record<string, string>
  const t = (key: string) => copy[key] || key
  const go = (next: Page) => { setPage(next); scrollTo({ top: 0, behavior: 'smooth' }) }
  const signOut = () => { localStorage.removeItem('agriconnect-session'); setSession(null); go('home') }
  useEffect(() => { localStorage.setItem('agriconnect-language', language); document.documentElement.lang = language }, [language])
  return <div className="app-shell">
    {!navigator.onLine && <div className="offline-bar"><CloudOff size={16} /> {t('offline')}</div>}
    <header className="site-header"><button className="brand" onClick={() => go(session?.user.role === 'FARMER' ? 'farmer' : session?.user.role === 'BUYER' ? 'buyer' : 'home')}><span className="brand-mark"><Sprout size={21} /></span>{t('brand')}</button><nav className="nav-links"><button onClick={() => go('home')}>{t('navHome')}</button>{session && <button onClick={() => go(session.user.role === 'FARMER' ? 'farmer' : 'buyer')}>{t('marketplace')}</button>}{session && <button onClick={() => go('orders')}>{t('orders')}</button>}</nav><div className="header-actions"><label className="language-select"><select value={language} onChange={e => setLanguage(e.target.value as Language)} aria-label={t('language')}><option value="en">English</option><option value="te">తెలుగు</option></select></label>{session && <button className="icon-button" onClick={signOut} title={t('signOut')}><LogOut size={18} /></button>}</div></header>
    {page === 'home' && <Home t={t} start={(nextRole, nextMode) => { setRole(nextRole); setAuthMode(nextMode); go('auth') }} />}
    {page === 'auth' && <Auth t={t} role={role} mode={authMode} setMode={setAuthMode} language={language} go={go} success={next => { setSession(next); localStorage.setItem('agriconnect-session', JSON.stringify(next)); go(next.user.role === 'FARMER' ? 'farmer' : 'buyer') }} />}
    {page === 'farmer' && session && <FarmerHome t={t} token={session.token} go={go} select={setSelectedListing} />}
    {page === 'buyer' && session && <BuyerHome t={t} token={session.token} go={go} select={setSelectedListing} />}
    {page === 'listing' && session && <ListingForm t={t} token={session.token} go={go} />}
    {page === 'browse' && session && <Browse t={t} go={go} select={setSelectedListing} />}
    {page === 'offer' && session && selectedListing && <OfferForm t={t} token={session.token} listing={selectedListing} go={go} />}
    {page === 'offers' && session && <Offers t={t} token={session.token} go={go} />}
    {page === 'orders' && session && <Orders t={t} token={session.token} go={go} />}
    {page === 'market-prices' && session?.user.role === 'FARMER' && <MarketPrices t={t} token={session.token} go={go} />}
    {page === 'storage' && session?.user.role === 'FARMER' && <LogisticsHub t={t} token={session.token} mode="storage" go={go} />}
    {page === 'storage-request' && session?.user.role === 'FARMER' && <StorageRequestForm t={t} token={session.token} go={go} />}
    {page === 'storage-requests' && session?.user.role === 'FARMER' && <RequestHistory t={t} token={session.token} mode="storage" go={go} />}
    {page === 'transport' && session?.user.role === 'FARMER' && <LogisticsHub t={t} token={session.token} mode="transport" go={go} />}
    {page === 'transport-request' && session?.user.role === 'FARMER' && <TransportRequestForm t={t} token={session.token} go={go} />}
    {page === 'transport-requests' && session?.user.role === 'FARMER' && <RequestHistory t={t} token={session.token} mode="transport" go={go} />}
    {page === 'crop-assistance' && session?.user.role === 'FARMER' && <CropAssistance t={t} token={session.token} go={go} />}
    <footer>{t('footer')}</footer>
  </div>
}

function Home({ t, start }: { t: (key: string) => string; start: (role: Role, mode: AuthMode) => void }) { return <main><section className="hero-section"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> {t('trusted')}</p><h1>{t('welcome')}</h1><p className="hero-intro">{t('intro')}</p><div className="role-grid"><Role title={t('farmerAccount')} text={t('farmerAccountText')} primary={t('registerFarmer')} secondary={t('loginFarmer')} icon={Sprout} onPrimary={() => start('FARMER', 'register')} onSecondary={() => start('FARMER', 'login')} /><Role title={t('buyerAccount')} text={t('buyerAccountText')} primary={t('registerBuyer')} secondary={t('loginBuyer')} icon={Users} onPrimary={() => start('BUYER', 'register')} onSecondary={() => start('BUYER', 'login')} /></div></div><div className="hero-art"><div className="sun" /><div className="crop-field crop-field-back" /><div className="crop-field crop-field-front" /><div className="plant plant-one"><i /><i /><i /></div><div className="plant plant-two"><i /><i /><i /></div></div></section></main> }
function Role({ title, text, primary, secondary, icon: Icon, onPrimary, onSecondary }: { title: string; text: string; primary: string; secondary: string; icon: typeof Sprout; onPrimary: () => void; onSecondary: () => void }) { return <article className="role-card"><div className="service-icon"><Icon size={22} /></div><h2>{title}</h2><p>{text}</p><button className="primary-button small-button" onClick={onPrimary}>{primary} <ArrowRight size={15} /></button><button className="text-button" onClick={onSecondary}>{secondary}</button></article> }

function Auth({ t, role, mode, setMode, language, go, success }: { t: (key: string) => string; role: Role; mode: AuthMode; setMode: (mode: AuthMode) => void; language: Language; go: (page: Page) => void; success: (session: Session) => void }) {
  const [values, setValues] = useState<Record<string, string>>({ language }); const [error, setError] = useState('')
  const update = (key: string, value: string) => setValues({ ...values, [key]: value })
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const result = mode === 'login' ? await api.login({ mobile: values.mobile, password: values.password, role }) : role === 'FARMER' ? await api.registerFarmer(values) : await api.registerBuyer(values); success(result) } catch (err) { setError(err instanceof Error ? err.message : 'Request failed') } }
  const register = mode === 'register'
  return <main className="form-page"><div className="form-intro"><button className="back-button" onClick={() => go('home')}><ArrowLeft size={14} /> {t('back')}</button><p className="eyebrow">{role === 'FARMER' ? t('farmerAccount') : t('buyerAccount')}</p><h1>{register ? (role === 'FARMER' ? t('registerFarmer') : t('buyerRegister')) : (role === 'FARMER' ? t('loginFarmer') : t('loginBuyer'))}</h1><p>{register ? (role === 'BUYER' ? t('buyerHelp') : t('registerHelp')) : t('loginHelp')}</p></div><form className="form-card" onSubmit={submit}><div className="auth-tabs"><button type="button" className={register ? 'active' : ''} onClick={() => setMode('register')}>{t('register')}</button><button type="button" className={!register ? 'active' : ''} onClick={() => setMode('login')}>{t('signIn')}</button></div>{register && <Field t={t} label={t('name')} value={values.name || ''} set={v => update('name', v)} required />}{register && role === 'BUYER' && <><Field t={t} label={t('email')} value={values.email || ''} set={v => update('email', v)} type="email" /><Field t={t} label={t('businessName')} value={values.businessName || ''} set={v => update('businessName', v)} required /><Select t={t} label={t('buyerType')} value={values.buyerType || ''} set={v => update('buyerType', v)} options={['wholesaler', 'retailer', 'processor', 'other']} /></>}{<Field t={t} label={t('mobile')} value={values.mobile || ''} set={v => update('mobile', v)} type="tel" required />}{register && <><Field t={t} label={t('state')} value={values.state || ''} set={v => update('state', v)} required /><Field t={t} label={t('district')} value={values.district || ''} set={v => update('district', v)} required /><Field t={t} label={role === 'BUYER' ? t('location') : t('village')} value={values[role === 'BUYER' ? 'location' : 'village'] || ''} set={v => update(role === 'BUYER' ? 'location' : 'village', v)} required /></>}{role === 'FARMER' && register && <><Field t={t} label={t('farmSize')} value={values.farmSize || ''} set={v => update('farmSize', v)} type="number" required /><Field t={t} label={t('crops')} value={values.crops || ''} set={v => update('crops', v)} required /></>}{<Field t={t} label={t('password')} value={values.password || ''} set={v => update('password', v)} type="password" required />}{error && <p className="error-message">{error}</p>}<p className="notice">{t('demoNote')}</p><button className="primary-button full-width">{register ? t('continue') : t('signIn')} <ArrowRight size={18} /></button></form></main>
}

function FarmerHome({ t, token, go, select }: Props) { const [listings, setListings] = useState<Listing[]>([]); useEffect(() => { api.myListings(token).then(x => setListings(x.listings)) }, [token]); return <main className="dashboard-page"><Header t={t} eyebrow={t('farmerProfile')} title={t('marketplace')} action={t('createListing')} onAction={() => go('listing')} /><Nav t={t} go={go} farmer /><div className="farmer-tools"><button className="market-tool-button" onClick={() => go('crop-assistance')}><ImagePlus size={18} /><span><strong>{t('cropAssistance')}</strong><small>{t('cropAssistanceHelp')}</small></span><ArrowRight size={16} /></button><button className="market-tool-button" onClick={() => go('market-prices')}><Search size={18} /><span><strong>{t('marketPrices')}</strong><small>{t('marketPricesHelp')}</small></span><ArrowRight size={16} /></button><button className="market-tool-button" onClick={() => go('storage')}><Package size={18} /><span><strong>{t('coldStorage')}</strong><small>{t('coldStorageHelp')}</small></span><ArrowRight size={16} /></button><button className="market-tool-button" onClick={() => go('transport')}><Truck size={18} /><span><strong>{t('transport')}</strong><small>{t('transportHelp')}</small></span><ArrowRight size={16} /></button></div><h2>{t('myListings')}</h2>{!listings.length ? <Empty title={t('noListings')} text={t('noListingsHelp')} /> : <div className="listing-grid">{listings.map(item => <Card key={item.id} t={t} listing={item} open={() => select(item)} remove={() => api.deleteListing(item.id, token).then(() => setListings(listings.filter(x => x.id !== item.id)))} />)}</div>}</main> }
function BuyerHome({ t, go, select }: Props) { return <main className="dashboard-page"><Header t={t} eyebrow={t('buyerProfile')} title={t('marketplace')} action={t('browseProduce')} onAction={() => go('browse')} /><Nav t={t} go={go} /><Browse t={t} go={go} select={select} /></main> }
function Header({ t, eyebrow, title, action, onAction }: { t: (key: string) => string; eyebrow: string; title: string; action: string; onAction: () => void }) { return <div className="dashboard-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{t('dashboardIntro')}</p></div><button className="primary-button" onClick={onAction}><Plus size={17} /> {action}</button></div> }
function Nav({ t, go, farmer = false }: { t: (key: string) => string; go: (page: Page) => void; farmer?: boolean }) { return <div className="market-nav"><button onClick={() => go(farmer ? 'farmer' : 'browse')}>{farmer ? t('myListings') : t('browseProduce')}</button><button onClick={() => go(farmer ? 'offers' : 'offers')}>{farmer ? t('offers') : t('myOffers')}</button><button onClick={() => go('orders')}>{t('orders')}</button></div> }

function ListingForm({ t, token, go }: { t: (key: string) => string; token: string; go: (page: Page) => void }) { const [v, setV] = useState<Record<string, string>>({ unit: 'kg', availabilityDate: new Date().toISOString().slice(0, 10) }); const [error, setError] = useState(''); const set = (key: string, value: string) => setV({ ...v, [key]: value }); const submit = async (e: FormEvent) => { e.preventDefault(); try { await api.createListing({ ...v, quantity: Number(v.quantity), expectedPrice: Number(v.expectedPrice) }, token); go('farmer') } catch (err) { setError(err instanceof Error ? err.message : 'Request failed') } }; return <main className="form-page"><div className="form-intro"><button className="back-button" onClick={() => go('farmer')}><ArrowLeft size={14} /> {t('back')}</button><p className="eyebrow">{t('sellProduce')}</p><h1>{t('createListing')}</h1><p>{t('listingHelp')}</p></div><form className="form-card" onSubmit={submit}><Field t={t} label={t('cropName')} value={v.cropName || ''} set={x => set('cropName', x)} required /><Field t={t} label={t('category')} value={v.category || ''} set={x => set('category', x)} required /><div className="form-row"><Field t={t} label={t('quantity')} value={v.quantity || ''} set={x => set('quantity', x)} type="number" required /><Select t={t} label={t('unit')} value={v.unit} set={x => set('unit', x)} options={['kg', 'quintal', 'tonne']} /></div><Field t={t} label={t('quality')} value={v.quality || ''} set={x => set('quality', x)} /><Field t={t} label={t('expectedPrice')} value={v.expectedPrice || ''} set={x => set('expectedPrice', x)} type="number" required /><Field t={t} label={t('availabilityDate')} value={v.availabilityDate} set={x => set('availabilityDate', x)} type="date" required /><Field t={t} label={t('pickupLocation')} value={v.pickupLocation || ''} set={x => set('pickupLocation', x)} required /><Field t={t} label={t('description')} value={v.description || ''} set={x => set('description', x)} /><p className="error-message">{error}</p><button className="primary-button full-width">{t('saveListing')} <Check size={18} /></button></form></main> }

function Browse({ t, go, select }: { t: (key: string) => string; go: (page: Page) => void; select: (listing: Listing) => void }) { const [items, setItems] = useState<Listing[]>([]); const [search, setSearch] = useState(''); const load = () => api.listings(search ? `?search=${encodeURIComponent(search)}` : '').then(x => setItems(x.listings)); useEffect(() => { api.listings().then(x => setItems(x.listings)) }, []); return <section><div className="search-row"><input value={search} onChange={e => setSearch(e.target.value)} placeholder={t('search')} /><button className="primary-button" onClick={load}><Search size={17} /> {t('searchAction')}</button></div>{!items.length ? <Empty title={t('noProduce')} text={t('noProduceHelp')} /> : <div className="listing-grid">{items.map(item => <Card key={item.id} t={t} listing={item} open={() => { select(item); go('offer') }} />)}</div>}</section> }
function OfferForm({ t, token, listing, go }: { t: (key: string) => string; token: string; listing: Listing; go: (page: Page) => void }) { const [price, setPrice] = useState(String(listing.expectedPrice)); const [quantity, setQuantity] = useState(String(listing.quantity)); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const submit = async (e: FormEvent) => { e.preventDefault(); try { await api.createOffer(listing.id, { offeredPrice: Number(price), requestedQuantity: Number(quantity), message }, token); go('buyer') } catch (err) { setError(err instanceof Error ? err.message : 'Request failed') } }; return <main className="form-page"><div className="form-intro"><button className="back-button" onClick={() => go('buyer')}><ArrowLeft size={14} /> {t('back')}</button><p className="eyebrow">{listing.cropName}</p><h1>{t('submitOffer')}</h1><p>{listing.quantity} {listing.unit} • ₹{listing.expectedPrice}</p></div><form className="form-card" onSubmit={submit}><Field t={t} label={t('offerPrice')} value={price} set={setPrice} type="number" required /><Field t={t} label={t('requestedQuantity')} value={quantity} set={setQuantity} type="number" required /><Field t={t} label={t('message')} value={message} set={setMessage} /><p className="error-message">{error}</p><button className="primary-button full-width">{t('sendOffer')} <ArrowRight size={18} /></button></form></main> }

function Offers({ t, token, go }: { t: (key: string) => string; token: string; go: (page: Page) => void }) { const [items, setItems] = useState<Offer[]>([]); useEffect(() => { api.myListings(token).then(async x => { const all = await Promise.all(x.listings.map(l => api.offersForListing(l.id, token))); setItems(all.flatMap(x => x.offers)) }).catch(() => api.myOffers(token).then(x => setItems(x.offers))) }, [token]); const respond = (id: string, status: string) => api.respondOffer(id, status, token).then(() => setItems(items.map(x => x.id === id ? { ...x, status } : x))); return <main className="dashboard-page"><button className="back-button" onClick={() => go('home')}><ArrowLeft size={14} /> {t('back')}</button><h1>{t('offers')}</h1>{!items.length ? <Empty title={t('noProduce')} text={t('noListingsHelp')} /> : <div className="offer-list">{items.map(item => <article className="offer-card" key={item.id}><strong>{item.buyer?.name || item.listing?.cropName || t('buyer')}</strong><span>{item.requestedQuantity} • ₹{item.offeredPrice}</span><b className="status">{item.status}</b>{item.status === 'PENDING' && <div><button className="primary-button small-button" onClick={() => respond(item.id, 'ACCEPTED')}>{t('accept')}</button><button className="text-button" onClick={() => respond(item.id, 'REJECTED')}>{t('reject')}</button></div>}</article>)}</div>}</main> }
function Orders({ t, token, go }: { t: (key: string) => string; token: string; go: (page: Page) => void }) { const [items, setItems] = useState<Order[]>([]); useEffect(() => { api.orders(token).then(x => setItems(x.orders)) }, [token]); return <main className="dashboard-page"><button className="back-button" onClick={() => go('home')}><ArrowLeft size={14} /> {t('back')}</button><h1>{t('myOrders')}</h1>{!items.length ? <Empty title={t('noOrders')} text={t('noOrdersHelp')} /> : <div className="offer-list">{items.map(item => <article className="offer-card" key={item.id}><strong>{item.listing.cropName}</strong><span>{item.quantity} {item.listing.unit} • ₹{item.agreedPrice}</span><b className="status">{item.status}</b></article>)}</div>}</main> }

function Card({ t, listing, open, remove }: { t: (key: string) => string; listing: Listing; open: () => void; remove?: () => void }) { return <article className="listing-card"><div className="listing-icon"><Package size={22} /></div><span className="status">{listing.status}</span><h2>{listing.cropName}</h2><p>{listing.quantity} {listing.unit} • ₹{listing.expectedPrice} / {listing.unit}</p><p>{listing.quality || t('available')} • {listing.pickupLocation}</p><button className="text-button" onClick={open}>{t('viewDetails')} <ArrowRight size={15} /></button>{remove && <button className="delete-button" onClick={remove}>{t('inactive')}</button>}</article> }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty-state"><LeafIcon /><h2>{title}</h2><p>{text}</p></div> }
function LeafIcon() { return <Sprout size={30} /> }
function Field({ t: _t, label, value, set, type = 'text', required = false }: { t: (key: string) => string; label: string; value: string; set: (value: string) => void; type?: string; required?: boolean }) { return <label className="field"><span>{label}{required && ' *'}</span><input type={type} value={value} required={required} onChange={e => set(e.target.value)} /></label> }
function Select({ t, label, value, set, options }: { t: (key: string) => string; label: string; value: string; set: (value: string) => void; options: string[] }) { return <label className="field"><span>{label}</span><select value={value} onChange={e => set(e.target.value)} required><option value="">{t('chooseOption') || 'Choose'}</option>{options.map(x => <option key={x} value={x}>{t(x) || x}</option>)}</select></label> }
type Props = { t: (key: string) => string; token: string; go: (page: Page) => void; select: (listing: Listing) => void }
