import { useEffect, useState } from 'react'
import { ArrowRight, Check, ChevronDown, CloudOff, Leaf, Menu, Sprout, Truck, Users, X } from 'lucide-react'
import { translations } from './i18n'
import type { Language, TranslationKey } from './i18n'

type Screen = 'home' | 'register' | 'login' | 'farm' | 'dashboard'
type Profile = { name: string; mobile: string; language: Language; state: string; district: string; village: string; farmSize: string; crops: string }
type FormValues = Partial<Profile> & { password?: string }
const cards = [['cropCare', Sprout], ['sellProduce', Leaf], ['marketPrices', Leaf], ['coldStorage', CloudOff], ['transport', Truck], ['buyers', Users]] as const

export default function App() {
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('agriconnect-language') as Language) || 'en')
  const [profile, setProfile] = useState<Profile | null>(() => JSON.parse(localStorage.getItem('agriconnect-profile') || 'null'))
  const [screen, setScreen] = useState<Screen>(() => localStorage.getItem('agriconnect-profile') ? 'dashboard' : 'home')
  const [offline, setOffline] = useState(!navigator.onLine)
  const [menuOpen, setMenuOpen] = useState(false)
  const t = (key: TranslationKey) => translations[language][key]
  useEffect(() => { localStorage.setItem('agriconnect-language', language); document.documentElement.lang = language }, [language])
  useEffect(() => { const update = () => setOffline(!navigator.onLine); addEventListener('online', update); addEventListener('offline', update); return () => { removeEventListener('online', update); removeEventListener('offline', update) } }, [])
  const navigate = (next: Screen) => { setScreen(next); setMenuOpen(false); scrollTo({ top: 0, behavior: 'smooth' }) }
  const save = (next: Profile) => { setProfile(next); localStorage.setItem('agriconnect-profile', JSON.stringify(next)); navigate('dashboard') }
  return <div className="app-shell">
    {offline && <div className="offline-bar"><CloudOff size={16} /> {t('offline')}</div>}
    <header className="site-header"><button className="brand" onClick={() => navigate('home')}><span className="brand-mark"><Sprout size={21} /></span>{t('brand')}</button><nav className={menuOpen ? 'nav-links open' : 'nav-links'}><button onClick={() => navigate('home')}>{t('navHome')}</button><a href="#how-it-works" onClick={() => setMenuOpen(false)}>{t('navAbout')}</a>{profile && <button onClick={() => navigate('dashboard')}>{t('dashboard')}</button>}</nav><div className="header-actions"><LanguageSelect language={language} onChange={setLanguage} label={t('language')} /><button className="icon-button menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menu">{menuOpen ? <X size={21} /> : <Menu size={21} />}</button></div></header>
    {screen === 'home' && <Home t={t} language={language} onLanguageChange={setLanguage} navigate={navigate} />}
    {screen === 'register' && <Register t={t} language={language} onLanguageChange={setLanguage} navigate={navigate} />}
    {screen === 'login' && <Login t={t} navigate={navigate} />}
    {screen === 'farm' && <Farm t={t} profile={profile} navigate={navigate} save={save} />}
    {screen === 'dashboard' && <Dashboard t={t} profile={profile} navigate={navigate} />}
    <footer>{t('footer')}</footer>
  </div>
}

function LanguageSelect({ language, onChange, label }: { language: Language; onChange: (language: Language) => void; label: string }) { return <label className="language-select"><span>{label}</span><select value={language} onChange={e => onChange(e.target.value as Language)} aria-label={label}><option value="en">English</option><option value="te">తెలుగు</option></select><ChevronDown size={14} /></label> }
function Home({ t, language, onLanguageChange, navigate }: { t: (key: TranslationKey) => string; language: Language; onLanguageChange: (language: Language) => void; navigate: (screen: Screen) => void }) { return <main><section className="hero-section"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> {t('trusted')}</p><h1>{t('welcome')}</h1><p className="hero-intro">{t('intro')}</p><div className="hero-actions"><button className="primary-button" onClick={() => navigate('register')}>{t('getStarted')} <ArrowRight size={18} /></button><button className="text-button" onClick={() => navigate('login')}>{t('signIn')}</button></div><div className="hero-language"><span>{t('language')}</span><LanguageSelect language={language} onChange={onLanguageChange} label={t('language')} /></div></div><div className="hero-art" aria-label="Illustration of a healthy field"><div className="sun" /><div className="crop-field crop-field-back" /><div className="crop-field crop-field-front" /><div className="plant plant-one"><i /><i /><i /></div><div className="plant plant-two"><i /><i /><i /></div><div className="hero-note"><Sprout size={19} /><span>Farmer-first<br /><strong>by design</strong></span></div></div></section><section className="steps-section" id="how-it-works"><div className="section-heading"><p className="eyebrow">AGRICULTURE, MADE CLEAR</p><h2>{t('learnMore')}</h2></div><div className="steps-grid"><Step number="01" title={t('stepOne')} text={t('stepOneText')} /><Step number="02" title={t('stepTwo')} text={t('stepTwoText')} /><Step number="03" title={t('stepThree')} text={t('stepThreeText')} /></div></section></main> }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <article className="step"><span className="step-number">{number}</span><h3>{title}</h3><p>{text}</p></article> }

function Register({ t, language, onLanguageChange, navigate }: { t: (key: TranslationKey) => string; language: Language; onLanguageChange: (language: Language) => void; navigate: (screen: Screen) => void }) { const [values, setValues] = useState<FormValues>({ language }); const [errors, setErrors] = useState<Record<string, string>>({}); const update = (key: keyof FormValues, value: string) => setValues({ ...values, [key]: value }); const submit = (e: React.FormEvent) => { e.preventDefault(); const next: Record<string, string> = {}; ['name', 'mobile', 'state', 'district', 'village'].forEach(key => { if (!values[key as keyof FormValues]) next[key] = t('required') }); if (values.mobile && !/^\d{10}$/.test(values.mobile)) next.mobile = t('invalidMobile'); setErrors(next); if (!Object.keys(next).length) { localStorage.setItem('agriconnect-draft', JSON.stringify(values)); navigate('farm') } }; return <FormLayout t={t} phase="01" title={t('register')} help={t('registerHelp')} back={() => navigate('home')}><form className="form-card" onSubmit={submit}><div className="form-card-top"><span className="form-step">01 <span>/ 02</span></span><LanguageSelect language={language} onChange={next => { onLanguageChange(next); update('language', next) }} label={t('language')} /></div><Field label={t('name')} value={values.name || ''} onChange={v => update('name', v)} error={errors.name} /><Field label={t('mobile')} value={values.mobile || ''} onChange={v => update('mobile', v)} error={errors.mobile} type="tel" /><div className="form-row"><Field label={t('state')} value={values.state || ''} onChange={v => update('state', v)} error={errors.state} /><Field label={t('district')} value={values.district || ''} onChange={v => update('district', v)} error={errors.district} /></div><Field label={t('village')} value={values.village || ''} onChange={v => update('village', v)} error={errors.village} /><button className="primary-button full-width">{t('continue')} <ArrowRight size={18} /></button></form></FormLayout> }
function Farm({ t, profile, navigate, save }: { t: (key: TranslationKey) => string; profile: Profile | null; navigate: (screen: Screen) => void; save: (profile: Profile) => void }) { const [values, setValues] = useState<FormValues>(() => profile || JSON.parse(localStorage.getItem('agriconnect-draft') || '{}')); const [errors, setErrors] = useState<Record<string, string>>({}); const update = (key: keyof FormValues, value: string) => setValues({ ...values, [key]: value }); const submit = (e: React.FormEvent) => { e.preventDefault(); const next: Record<string, string> = {}; if (!values.farmSize) next.farmSize = t('required'); else if (Number(values.farmSize) <= 0) next.farmSize = t('invalidNumber'); if (!values.crops) next.crops = t('required'); setErrors(next); if (!Object.keys(next).length) { localStorage.removeItem('agriconnect-draft'); save(values as Profile) } }; return <FormLayout t={t} phase="02" title={t('farmDetails')} help={t('farmHelp')} back={() => navigate('register')}><form className="form-card" onSubmit={submit}><div className="farm-icon"><Sprout size={25} /></div><Field label={t('farmSize')} value={values.farmSize || ''} onChange={v => update('farmSize', v)} error={errors.farmSize} type="number" /><Field label={t('crops')} hint={t('cropsHint')} value={values.crops || ''} onChange={v => update('crops', v)} error={errors.crops} /><button className="primary-button full-width">{t('saveProfile')} <Check size={18} /></button></form></FormLayout> }
function FormLayout({ t, phase, title, help, back, children }: { t: (key: TranslationKey) => string; phase: string; title: string; help: string; back: () => void; children: React.ReactNode }) { return <main className="form-page"><div className="form-intro"><button className="back-button" onClick={back}>← {t('back')}</button><p className="eyebrow">PHASE 1 / {phase}</p><h1>{title}</h1><p>{help}</p></div>{children}</main> }
function Login({ t, navigate }: { t: (key: TranslationKey) => string; navigate: (screen: Screen) => void }) { const [mobile, setMobile] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const submit = (e: React.FormEvent) => { e.preventDefault(); if (!/^\d{10}$/.test(mobile)) return setError(t('invalidMobile')); if (password.length < 6) return setError(t('invalidPassword')); navigate('dashboard') }; return <FormLayout t={t} phase="DEMO" title={t('login')} help={t('loginHelp')} back={() => navigate('home')}><form className="form-card" onSubmit={submit}><div className="notice">{t('mockNotice')}</div><Field label={t('mobile')} value={mobile} onChange={setMobile} type="tel" /><Field label={t('password')} value={password} onChange={setPassword} type="password" />{error && <p className="error-message">{error}</p>}<button className="primary-button full-width">{t('signIn')} <ArrowRight size={18} /></button></form></FormLayout> }
function Field({ label, value, onChange, error, hint, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; error?: string; hint?: string; type?: string }) { return <label className="field"><span>{label}</span><input type={type} value={value} onChange={e => onChange(e.target.value)} aria-invalid={Boolean(error)} />{hint && <small>{hint}</small>}{error && <small className="error-message">{error}</small>}</label> }
function Dashboard({ t, profile, navigate }: { t: (key: TranslationKey) => string; profile: Profile | null; navigate: (screen: Screen) => void }) { return <main className="dashboard-page"><div className="dashboard-heading"><div><p className="eyebrow">YOUR FARM WORKSPACE</p><h1>{t('dashboard')}</h1><p>{t('dashboardIntro')}</p></div><button className="outline-button" onClick={() => { localStorage.removeItem('agriconnect-profile'); navigate('home') }}>{t('signOut')}</button></div><div className="profile-banner"><div className="avatar">{profile?.name?.slice(0, 1).toUpperCase() || 'F'}</div><div><strong>{profile?.name || 'Farmer'}</strong><span>{t('profileReadyText')}</span></div><Check size={21} /></div><div className="service-grid">{cards.map(([key, Icon]) => <article className="service-card" key={key}><div className="service-icon"><Icon size={22} /></div><div><h2>{t(key)}</h2><p>{t(`${key}Text` as TranslationKey)}</p></div><span className="coming-soon">{t('comingSoon')}</span></article>)}</div></main> }
