import { useEffect, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { ArrowLeft, ArrowRight, Check, MapPin, Package, Truck } from 'lucide-react'
import { api } from './api'
import type { ColdStorageFacility, StorageRequest, TransportProvider, TransportRequest } from './api'
import type { Language } from './i18n'
import './logistics.css'
import { SpeakButton } from './voice/SpeakButton'

type Text = (key: string) => string
type Page = 'farmer' | 'storage' | 'storage-request' | 'transport' | 'transport-request' | 'storage-requests' | 'transport-requests'
type Props = { t: Text; token: string; language: Language; go: (page: Page) => void }

export function LogisticsHub({ t, mode, go }: Props & { mode: 'storage' | 'transport' }) { const [search, setSearch] = useState(''); const [facilities, setFacilities] = useState<ColdStorageFacility[]>([]); const [providers, setProviders] = useState<TransportProvider[]>([]); const [loading, setLoading] = useState(true); const load = () => { setLoading(true); if (mode === 'storage') api.coldStorage({ location: search }).then(data => setFacilities(data.facilities || [])).finally(() => setLoading(false)); else api.transportProviders({ location: search }).then(data => setProviders(data.providers || [])).finally(() => setLoading(false)) }; useEffect(() => { if (mode === 'storage') api.coldStorage().then(data => setFacilities(data.facilities || [])).finally(() => setLoading(false)); else api.transportProviders().then(data => setProviders(data.providers || [])).finally(() => setLoading(false)) }, [mode]); return <main className="dashboard-page logistics-page"><button className="back-button" onClick={() => go('farmer')}><ArrowLeft size={14} /> {t('back')}</button><div className="dashboard-heading"><div><p className="eyebrow">{mode === 'storage' ? t('coldStorage') : t('transport')}</p><h1>{mode === 'storage' ? t('storageDirectory') : t('transportDirectory')}</h1><p>{mode === 'storage' ? t('coldStorageHelp') : t('transportHelp')}</p></div><button className="outline-button" onClick={load}>{mode === 'storage' ? t('searchFacilities') : t('searchProviders')}</button></div><div className="logistics-search"><input value={search} onChange={event => setSearch(event.target.value)} placeholder={t('locationSearch')} /><button className="primary-button" onClick={load}>{mode === 'storage' ? t('searchFacilities') : t('searchProviders')}</button></div>{loading ? <div className="empty-state">{t('loadingLogistics')}</div> : mode === 'storage' ? <div className="logistics-grid">{facilities.map(facility => <FacilityCard key={facility.id} t={t} facility={facility} go={go} />)}</div> : <div className="logistics-grid">{providers.map(provider => <ProviderCard key={provider.id} t={t} provider={provider} go={go} />)}</div>}</main> }
function FacilityCard({ t, facility, go }: { t: Text; facility: ColdStorageFacility; go: (page: Page) => void }) { return <article className="logistics-card"><span className="sample-badge">{t('sampleInfo')}</span><MapPin size={24} className="logistics-icon" /><h2>{facility.name}</h2><p>{facility.location}, {facility.district}, {facility.state}</p><p><strong>{t('supportedCrops')}:</strong> {facility.supportedCrops}</p><p><strong>{t('capacity')}:</strong> {facility.capacity ? `${facility.capacity} ${facility.capacityUnit}` : '-'}</p><small>{t('noDistance')}</small><SpeakButton text={`${facility.name}. ${facility.location}, ${facility.district}. ${t('supportedCrops')}: ${facility.supportedCrops}.`} language="en" label={t('speak')} /><button className="text-button" onClick={() => go('storage-request')}>{t('requestStorage')} <ArrowRight size={15} /></button></article> }
function ProviderCard({ t, provider, go }: { t: Text; provider: TransportProvider; go: (page: Page) => void }) { return <article className="logistics-card"><span className="sample-badge">{t('sampleInfo')}</span><Truck size={24} className="logistics-icon" /><h2>{provider.name}</h2><p><strong>{t('vehicleType')}:</strong> {provider.vehicleType}</p><p><strong>{t('capacity')}:</strong> {provider.capacity ? `${provider.capacity} ${provider.capacityUnit}` : '-'}</p><p><strong>{t('serviceAreas')}:</strong> {provider.serviceAreas}</p><small>{t('futureProvider')}</small><SpeakButton text={`${provider.name}. ${t('vehicleType')}: ${provider.vehicleType}. ${t('serviceAreas')}: ${provider.serviceAreas}.`} language="en" label={t('speak')} /><button className="text-button" onClick={() => go('transport-request')}>{t('requestTransport')} <ArrowRight size={15} /></button></article> }

export function StorageRequestForm({ t, token, go }: Props) { const [facilities, setFacilities] = useState<ColdStorageFacility[]>([]); const [v, setV] = useState<Record<string, string>>({ unit: 'kg' }); const [error, setError] = useState(''); useEffect(() => { api.coldStorage().then(data => setFacilities(data.facilities || [])) }, []); const set = (key: string, value: string) => setV({ ...v, [key]: value }); const submit = async (event: FormEvent) => { event.preventDefault(); if (v.endDate <= v.startDate) return setError(t('dateOrder')); try { await api.storageRequest({ ...v, quantity: Number(v.quantity) }, token); go('storage-requests') } catch (err) { setError(err instanceof Error ? err.message : t('requestFailed')) } }; return <RequestLayout t={t} title={t('storageRequest')} help={t('storageRequestHelp')} back={() => go('storage')}><form className="form-card" onSubmit={submit}><Select t={t} label={t('chooseFacility')} value={v.facilityId || ''} set={x => set('facilityId', x)} options={facilities.map(x => x.id)} labels={Object.fromEntries(facilities.map(x => [x.id, x.name]))} /><Field t={t} label={t('cropSearch')} value={v.cropName || ''} set={x => set('cropName', x)} required /><div className="form-row"><Field t={t} label={t('quantity')} value={v.quantity || ''} set={x => set('quantity', x)} type="number" required /><Field t={t} label={t('unit')} value={v.unit} set={x => set('unit', x)} required /></div><div className="form-row"><Field t={t} label={t('startDate')} value={v.startDate || ''} set={x => set('startDate', x)} type="date" required /><Field t={t} label={t('endDate')} value={v.endDate || ''} set={x => set('endDate', x)} type="date" required /></div><Field t={t} label={t('notes')} value={v.notes || ''} set={x => set('notes', x)} /><p className="notice">{t('pendingNotice')}</p><p className="error-message">{error}</p><button className="primary-button full-width">{t('submitRequest')} <Check size={17} /></button></form></RequestLayout> }
export function TransportRequestForm({ t, token, go }: Props) { const [providers, setProviders] = useState<TransportProvider[]>([]); const [v, setV] = useState<Record<string, string>>({ unit: 'kg' }); const [error, setError] = useState(''); useEffect(() => { api.transportProviders().then(data => setProviders(data.providers || [])) }, []); const set = (key: string, value: string) => setV({ ...v, [key]: value }); const submit = async (event: FormEvent) => { event.preventDefault(); try { await api.transportRequest({ ...v, quantity: Number(v.quantity) }, token); go('transport-requests') } catch (err) { setError(err instanceof Error ? err.message : t('requestFailed')) } }; return <RequestLayout t={t} title={t('transportRequest')} help={t('transportRequestHelp')} back={() => go('transport')}><form className="form-card" onSubmit={submit}><Select t={t} label={t('chooseProvider')} value={v.providerId || ''} set={x => set('providerId', x)} options={providers.map(x => x.id)} labels={Object.fromEntries(providers.map(x => [x.id, x.name]))} /><Field t={t} label={t('cropSearch')} value={v.cropName || ''} set={x => set('cropName', x)} required /><div className="form-row"><Field t={t} label={t('quantity')} value={v.quantity || ''} set={x => set('quantity', x)} type="number" required /><Field t={t} label={t('unit')} value={v.unit} set={x => set('unit', x)} required /></div><Field t={t} label={t('pickupLocation')} value={v.pickupLocation || ''} set={x => set('pickupLocation', x)} required /><Field t={t} label={t('destination')} value={v.destination || ''} set={x => set('destination', x)} required /><Field t={t} label={t('pickupDate')} value={v.pickupDate || ''} set={x => set('pickupDate', x)} type="date" required /><Field t={t} label={t('vehicleRequirements')} value={v.vehicleRequirements || ''} set={x => set('vehicleRequirements', x)} /><Field t={t} label={t('notes')} value={v.notes || ''} set={x => set('notes', x)} /><p className="notice">{t('pendingNotice')}</p><p className="error-message">{error}</p><button className="primary-button full-width">{t('submitRequest')} <Check size={17} /></button></form></RequestLayout> }
function RequestLayout({ t, title, help, back, children }: { t: Text; title: string; help: string; back: () => void; children: ReactNode }) { return <main className="form-page"><div className="form-intro"><button className="back-button" onClick={back}><ArrowLeft size={14} /> {t('back')}</button><p className="eyebrow">{t('farmerProfile')}</p><h1>{title}</h1><p>{help}</p></div>{children}</main> }
export function RequestHistory({ t, token, go, mode, language }: Props & { mode: 'storage' | 'transport' }) { const [items, setItems] = useState<(StorageRequest | TransportRequest)[]>([]); useEffect(() => { (mode === 'storage' ? api.myStorageRequests(token) : api.myTransportRequests(token)).then(data => setItems(data.requests)) }, [mode, token]); const cancel = (id: string) => (mode === 'storage' ? api.cancelStorageRequest(id, token) : api.cancelTransportRequest(id, token)).then(() => setItems(items.map(item => item.id === id ? { ...item, status: 'CANCELLED' } : item))); return <main className="dashboard-page"><button className="back-button" onClick={() => go('farmer')}><ArrowLeft size={14} /> {t('back')}</button><h1>{mode === 'storage' ? t('storageRequestHistory') : t('transportRequestHistory')}</h1>{!items.length ? <div className="empty-state"><Package size={30} /><h2>{t('noRequests')}</h2><p>{t('noRequestsHelp')}</p></div> : <div className="request-list">{items.map(item => <article className="request-card" key={item.id}><b>{item.cropName}</b><span>{item.quantity} {item.unit} · {item.status}</span><small>{mode === 'storage' ? (item as StorageRequest).facility?.name : `${(item as TransportRequest).pickupLocation} -> ${(item as TransportRequest).destination}`}</small><span className="status">{item.status}</span><SpeakButton text={`${item.cropName}. ${item.quantity} ${item.unit}. ${item.status}.`} language={language} token={token} label={t('speak')} />{['PENDING', 'ACCEPTED'].includes(item.status) && <button className="text-button" onClick={() => cancel(item.id)}>{t('cancelRequest')}</button>}</article>)}</div>}<p className="notice">{t('adminWorkflow')}</p></main> }
function Field({ t: _t, label, value, set, type = 'text', required = false }: { t: Text; label: string; value: string; set: (value: string) => void; type?: string; required?: boolean }) { return <label className="field"><span>{label}{required && ' *'}</span><input type={type} value={value} required={required} onChange={event => set(event.target.value)} /></label> }
function Select({ t, label, value, set, options, labels = {} }: { t: Text; label: string; value: string; set: (value: string) => void; options: string[]; labels?: Record<string, string> }) { return <label className="field"><span>{label}</span><select value={value} required onChange={event => set(event.target.value)}><option value="">{t('chooseOption') || 'Choose'}</option>{options.map(option => <option key={option} value={option}>{labels[option] || option}</option>)}</select></label> }
