import { useEffect, useState } from 'react'
import { ArrowLeft, Calculator, History, RefreshCw, Search } from 'lucide-react'
import { api } from './api'
import type { Listing, MarketPriceRecord, Offer, PriceResponse } from './api'
import './marketPrices.css'

type Text = (key: string) => string
type Props = { t: Text; token: string; go: (page: 'farmer') => void }

const money = (value: number | null | undefined) => value == null ? '-' : `₹${value.toLocaleString('en-IN')}`
const dateText = (value: string) => new Date(value).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })

export function MarketPrices({ t, token, go }: Props) {
  const [crop, setCrop] = useState('Paddy')
  const [location, setLocation] = useState('')
  const [result, setResult] = useState<PriceResponse | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [tab, setTab] = useState<'comparison' | 'calculator' | 'history' | 'offers'>('comparison')
  const load = async () => { setLoading(true); setError(''); try { setResult(await api.marketPrices({ crop, market: location })) } catch (err) { setError(err instanceof Error ? err.message : t('priceRequestFailed')) } finally { setLoading(false) } }
  useEffect(() => { api.marketPrices({ crop: 'Paddy' }).then(setResult).catch(err => setError(err instanceof Error ? err.message : t('priceRequestFailed'))).finally(() => setLoading(false)) }, [t])
  return <main className="dashboard-page market-price-page"><button className="back-button" onClick={() => go('farmer')}><ArrowLeft size={14} /> {t('back')}</button><div className="dashboard-heading"><div><p className="eyebrow">{t('marketPrices')}</p><h1>{t('marketIntelligence')}</h1><p>{t('marketPricesHelp')}</p></div><button className="outline-button" onClick={() => void load()}><RefreshCw size={15} /> {t('refreshPrices')}</button></div><form className="market-filters" onSubmit={event => { event.preventDefault(); void load() }}><label><span>{t('crop')}</span><input value={crop} onChange={event => setCrop(event.target.value)} placeholder={t('cropPlaceholder')} /></label><label><span>{t('marketLocation')}</span><input value={location} onChange={event => setLocation(event.target.value)} placeholder={t('marketPlaceholder')} /></label><button className="primary-button"><Search size={16} /> {t('searchPrices')}</button></form>{error && <p className="error-message">{error}</p>}{loading ? <div className="empty-state">{t('loadingPrices')}</div> : result && <><PriceMeta t={t} result={result} /><div className="price-tabs"><button className={tab === 'comparison' ? 'active' : ''} onClick={() => setTab('comparison')}>{t('compareMarkets')}</button><button className={tab === 'calculator' ? 'active' : ''} onClick={() => setTab('calculator')}>{t('netProceeds')}</button><button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}>{t('historicalPrices')}</button><button className={tab === 'offers' ? 'active' : ''} onClick={() => setTab('offers')}>{t('offerComparison')}</button></div>{tab === 'comparison' && <PriceTable t={t} records={result.records} />}{tab === 'calculator' && <NetCalculator t={t} defaultPrice={result.records[0]?.modalPrice || 0} />}{tab === 'history' && <HistoryTable t={t} records={result.records} />}{tab === 'offers' && <OfferComparison t={t} token={token} crop={crop} />}</>}</main>
}

function PriceMeta({ t, result }: { t: Text; result: PriceResponse }) { return <div className="data-meta"><span className="sample-badge">{result.dataStatus === 'SAMPLE' ? t('sampleData') : t('liveData')}</span><span>{t('source')}: {result.source}</span><span>{t('retrievedAt')}: {new Date(result.retrievedAt).toLocaleString('en-IN')}</span></div> }
function PriceTable({ t, records }: { t: Text; records: MarketPriceRecord[] }) { if (!records.length) return <div className="empty-state"><h2>{t('noPriceData')}</h2><p>{t('noPriceDataHelp')}</p></div>; return <div className="table-wrap"><table><thead><tr><th>{t('market')}</th><th>{t('location')}</th><th>{t('minPrice')}</th><th>{t('maxPrice')}</th><th>{t('modalPrice')}</th><th>{t('unit')}</th><th>{t('priceDate')}</th></tr></thead><tbody>{records.map(record => <tr key={record.id}><td>{record.market.name}</td><td>{record.market.district}, {record.market.state}</td><td>{money(record.minPrice)}</td><td>{money(record.maxPrice)}</td><td className="strong-price">{money(record.modalPrice)}</td><td>{record.unit}{record.grade ? ` · ${record.grade}` : ''}</td><td>{dateText(record.priceDate)}</td></tr>)}</tbody></table></div> }
function HistoryTable({ t, records }: { t: Text; records: MarketPriceRecord[] }) { return <section className="history-panel"><div className="section-heading"><div><p className="eyebrow"><History size={14} /> {t('historicalPrices')}</p><h2>{t('historicalView')}</h2></div><span>{t('sampleData')}</span></div><PriceTable t={t} records={records} /></section> }
function NetCalculator({ t, defaultPrice }: { t: Text; defaultPrice: number }) { const [quantity, setQuantity] = useState(''); const [price, setPrice] = useState(String(defaultPrice)); const [transport, setTransport] = useState(''); const [storage, setStorage] = useState(''); const [other, setOther] = useState(''); const gross = Number(quantity || 0) * Number(price || 0); const totalCosts = Number(transport || 0) + Number(storage || 0) + Number(other || 0); return <section className="calculator"><div className="calculator-head"><Calculator size={22} /><div><h2>{t('netProceeds')}</h2><p>{t('estimateNote')}</p></div></div><div className="calculator-grid"><CalcInput label={t('quantity')} value={quantity} set={setQuantity} /><CalcInput label={t('pricePerUnit')} value={price} set={setPrice} /><CalcInput label={t('transportCost')} value={transport} set={setTransport} /><CalcInput label={t('storageCost')} value={storage} set={setStorage} /><CalcInput label={t('otherCosts')} value={other} set={setOther} /></div><div className="calculation-result"><div><span>{t('grossProceeds')}</span><strong>{money(gross)}</strong></div><div><span>{t('enteredCosts')}</span><strong>{money(totalCosts)}</strong></div><div className="net-total"><span>{t('estimatedNet')}</span><strong>{money(gross - totalCosts)}</strong></div></div></section> }
function CalcInput({ label, value, set }: { label: string; value: string; set: (value: string) => void }) { return <label className="field"><span>{label}</span><input type="number" min="0" value={value} onChange={event => set(event.target.value)} /></label> }
function OfferComparison({ t, token, crop }: { t: Text; token: string; crop: string }) { const [offers, setOffers] = useState<(Offer & { listing?: Listing })[]>([]); const [prices, setPrices] = useState<MarketPriceRecord[]>([]); useEffect(() => { api.myListings(token).then(async data => { const all = (await Promise.all(data.listings.filter(item => item.cropName.toLowerCase().includes(crop.toLowerCase())).map(item => api.offersForListing(item.id, token)))).flatMap(item => item.offers); setOffers(all); const response = await api.marketPrices({ crop }); setPrices(response.records) }).catch(() => undefined) }, [token, crop]); if (!offers.length) return <div className="empty-state"><h2>{t('noOfferComparison')}</h2><p>{t('noOfferComparisonHelp')}</p></div>; const bestMarket = prices.find(item => item.modalPrice != null)?.modalPrice || 0; return <div className="offer-comparison-grid">{offers.map(offer => <article className="offer-compare-card" key={offer.id}><span>{offer.buyer?.name || t('buyer')}</span><h2>{money(offer.offeredPrice)} <small>/ {offer.listing?.unit || 'unit'}</small></h2><p>{t('marketReference')}: {money(bestMarket)}</p><b className={offer.offeredPrice >= bestMarket ? 'positive-difference' : 'negative-difference'}>{bestMarket ? `${offer.offeredPrice >= bestMarket ? '+' : ''}${money(offer.offeredPrice - bestMarket)}` : '-'}</b><small>{offer.requestedQuantity} {offer.listing?.unit || ''} · {t('pendingDecision')}</small></article>)}</div> }
