export const phase5Text = {
  en: {
    cropAssistance: 'Crop Assistance', cropAssistanceHelp: 'Upload a crop photo for a development demo image review.', cropPhoto: 'Crop photograph', chooseCrop: 'Select crop', analyzeImage: 'Review image', replaceImage: 'Replace image', chooseImage: 'Choose image', supportedImageTypes: 'JPEG, PNG, or WebP up to 5 MB.', demoResult: 'Development demo result', notRealDiagnosis: 'This is not a real AI diagnosis or confirmed disease identification.', possibleResult: 'Possible result', confidence: 'Confidence', lowConfidence: 'Low-confidence result', lowConfidenceText: 'This image review is inconclusive. Do not make treatment decisions from this result.', expertHelp: 'For a reliable assessment, contact your local KVK or a qualified agricultural expert.', history: 'Diagnosis history', noDiagnosisHistory: 'No crop reviews yet', noDiagnosisHistoryHelp: 'Your submitted image reviews will appear here.', processing: 'Reviewing image...', completed: 'Review complete', unsupportedCrop: 'Crop not supported', unsupportedCropText: 'The current demo provider does not support this crop yet.', imageRequired: 'Please select an image.', cropRequired: 'Please select a crop.', invalidImage: 'Use a readable JPEG, PNG, or WebP image up to 5 MB.', diagnosisFailed: 'The image review could not be completed. Please try again.', guidanceOnly: 'General guidance only', guidanceText: 'Inspect the crop in good light and speak with a qualified agricultural expert before taking action.', selectCrop: 'Choose a crop', paddy: 'Paddy', cotton: 'Cotton', chilli: 'Chilli', maize: 'Maize', tomato: 'Tomato', otherCrop: 'Other crop', demoProvider: 'Mock demo provider', modelVersion: 'Model version', kvkHelp: 'KVK / expert help', assistanceUnavailable: 'AI assistance is currently unavailable.', keepPrivate: 'Your image is stored privately with your farmer record.',
    confidenceLimit: 'This is an AI estimate, not a validated probability.', observedSymptoms: 'Observed signs', notEnoughEvidence: 'Not enough visible evidence.', explanation: 'Explanation', nextSteps: 'Recommended next steps',
  },
  te: {
    cropAssistance: 'పంట సహాయం', cropAssistanceHelp: 'అభివృద్ధి డెమో చిత్ర సమీక్ష కోసం పంట ఫోటోను అప్‌లోడ్ చేయండి.', cropPhoto: 'పంట ఫోటో', chooseCrop: 'పంట ఎంచుకోండి', analyzeImage: 'చిత్రాన్ని సమీక్షించండి', replaceImage: 'చిత్రాన్ని మార్చండి', chooseImage: 'చిత్రం ఎంచుకోండి', supportedImageTypes: 'JPEG, PNG లేదా WebP, గరిష్ఠం 5 MB.', demoResult: 'అభివృద్ధి డెమో ఫలితం', notRealDiagnosis: 'ఇది నిజమైన AI నిర్ధారణ లేదా ఖచ్చితమైన వ్యాధి గుర్తింపు కాదు.', possibleResult: 'సంభావ్య ఫలితం', confidence: 'నమ్మక స్థాయి', lowConfidence: 'తక్కువ నమ్మక స్థాయి ఫలితం', lowConfidenceText: 'ఈ చిత్ర సమీక్ష స్పష్టంగా లేదు. ఈ ఫలితంతో చికిత్స నిర్ణయాలు తీసుకోవద్దు.', expertHelp: 'విశ్వసనీయమైన అంచనా కోసం స్థానిక KVK లేదా అర్హత కలిగిన వ్యవసాయ నిపుణుడిని సంప్రదించండి.', history: 'నిర్ధారణ చరిత్ర', noDiagnosisHistory: 'ఇంకా పంట సమీక్షలు లేవు', noDiagnosisHistoryHelp: 'మీ చిత్ర సమీక్షలు ఇక్కడ కనిపిస్తాయి.', processing: 'చిత్రాన్ని సమీక్షిస్తోంది...', completed: 'సమీక్ష పూర్తయింది', unsupportedCrop: 'పంటకు మద్దతు లేదు', unsupportedCropText: 'ప్రస్తుత డెమో ప్రొవైడర్‌కు ఈ పంటకు ఇంకా మద్దతు లేదు.', imageRequired: 'దయచేసి చిత్రాన్ని ఎంచుకోండి.', cropRequired: 'దయచేసి పంటను ఎంచుకోండి.', invalidImage: '5 MB లోపు చదవగల JPEG, PNG లేదా WebP చిత్రాన్ని ఉపయోగించండి.', diagnosisFailed: 'చిత్ర సమీక్ష పూర్తి కాలేదు. మళ్లీ ప్రయత్నించండి.', guidanceOnly: 'సాధారణ మార్గదర్శకం మాత్రమే', guidanceText: 'మంచి వెలుతురులో పంటను పరిశీలించి, చర్య తీసుకునే ముందు అర్హత కలిగిన వ్యవసాయ నిపుణుడిని సంప్రదించండి.', selectCrop: 'పంట ఎంచుకోండి', paddy: 'వరి', cotton: 'పత్తి', chilli: 'మిరప', maize: 'మొక్కజొన్న', tomato: 'టమాటా', otherCrop: 'ఇతర పంట', demoProvider: 'మాక్ డెమో ప్రొవైడర్', modelVersion: 'మోడల్ వెర్షన్', kvkHelp: 'KVK / నిపుణుల సహాయం', assistanceUnavailable: 'AI సహాయం ప్రస్తుతం అందుబాటులో లేదు.', keepPrivate: 'మీ చిత్రం మీ రైతు రికార్డుతో ప్రైవేట్‌గా నిల్వ చేయబడింది.',
    confidenceLimit: 'ఇది AI అంచనా మాత్రమే; శాస్త్రీయంగా ధృవీకరించిన సంభావ్యత కాదు.', observedSymptoms: 'గమనించిన లక్షణాలు', notEnoughEvidence: 'సరిపడే దృశ్య ఆధారాలు లేవు.', explanation: 'వివరణ', nextSteps: 'తదుపరి సూచించిన చర్యలు',
  },
} as const
